name: OSV-Scanner Scheduled Scan

on:
  schedule:
    - cron: '42 3 * * *' # run at 2.42pm AEDT (3.42am UTC) every day
# Change "main" to your default branch if you use a different name, i.e. "master"
  push:
    branches: [ main ]

permissions:
  # Require writing security events to upload SARIF file to security tab
  security-events: write
  # Only need to read contents
  contents: read

jobs:
  scan-scheduled:
    uses: "google/osv-scanner/.github/workflows/osv-scanner-reusable.yml@main"
